import Image from 'next/image';
import Link from 'next/link';
import { profile } from '@/content/profile';
import { workingModel } from '@/content/capabilities';
import { ProfessionalSnapshot } from '@/components/profile/professional-snapshot';
import { Conversation } from '@/components/content/conversation';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('About','Eduardo Merino is a Software Engineer working across full-stack systems and applied AI.','/about');
export default function AboutPage(){return <main id="main-content" tabIndex={-1}><section className="container section about-intro"><div><p className="eyebrow accent">The builder</p><h1>Hi, I’m<br/>Eduardo Merino.</h1><p className="lead">{profile.proposition}</p><p className="about-personal">I work across the interface, the application and the data behind it. I care about understanding the real problem, making the important decisions explicit and carrying the implementation through to a usable result.</p><Link href="/contact" className="button primary">Start a conversation <span aria-hidden="true">↗</span></Link></div><figure className="about-portrait"><Image src={profile.portrait} alt="Eduardo Merino, Software Engineer" width={480} height={594} sizes="(max-width: 767px) 85vw, 420px" priority/><figcaption>Eduardo Merino / {profile.role} · {profile.specialty}</figcaption></figure></section><section className="container recruiter-strip about-snapshot"><ProfessionalSnapshot education/></section><section className="professional-section section"><div className="container split"><div><p className="eyebrow accent">What connects the work</p><h2>Different domains.<br/>The same responsibility.</h2></div><div className="case-body"><p className="lead">Vehicle signals, financial evidence, territorial planning and editorial workflows all have something in common: the software has to respect the reality underneath it.</p><p className="about-personal">My professional contribution record covers implementation and hardening in infrastructure software. My independent systems explore product engineering, data integrity, automation and applied AI.</p><Link className="text-link" href="/systems/infrastructure-site-mapper">Professional contribution record <span aria-hidden="true">↗</span></Link></div></div></section><section className="container section" id="method"><div className="section-head"><div><p className="eyebrow accent">The working method</p><h2>Clarity before code.<br/>Evidence after it.</h2></div><p>Understand, structure, build, verify and evolve. The next decision should have a reason, and the next claim should have support.</p></div><ol className="working-model">{workingModel.map((step,i)=><li key={step.title}><span className="eyebrow">0{i+1}</span><h3>{step.title}</h3><p>{step.detail}</p></li>)}</ol></section><section className="paper section"><div className="container split"><div><p className="eyebrow">A few things I keep true</p><h2>Good software can<br/>explain itself.</h2></div><ul className="about-rules"><li>Understand an existing system before deciding what to change.</li><li>Make missing information visible.</li><li>Keep ownership and responsibility explicit.</li><li>Let testing expose limitations, then act on them.</li><li>Keep the simple path simple, with depth available when it helps.</li></ul></div></section><Conversation/></main>}
