export const cvEngineCaseEs = {
  id: "02",
  name: "CV Engine",
  label: "INTELIGENCIA DE APLICACIONES",
  role: "Constructor principal",
  state: "ACTIVO",
  thesis:
    "Un sistema de decisión para comparar evidencia profesional con la verdad de una oportunidad sin permitir que datos de mercado, inferencias o recomendaciones reescriban lo que el candidato realmente puede demostrar.",
  truthLayers: [
    {
      id: "career",
      index: "01",
      title: "HECHO PROFESIONAL",
      detail: "Evidencia y afirmaciones del lado del candidato.",
      boundary: "LO QUE SE PUEDE DEMOSTRAR",
    },
    {
      id: "market",
      index: "02",
      title: "HECHO DE MERCADO",
      detail: "Lo que una oferta/fuente dice explícitamente.",
      boundary: "LO QUE DIJO LA FUENTE",
    },
    {
      id: "analysis",
      index: "03",
      title: "ANÁLISIS DERIVADO",
      detail: "Matching, normalización e interpretación.",
      boundary: "LO QUE CALCULÓ EL SISTEMA",
    },
    {
      id: "recommendation",
      index: "04",
      title: "RECOMENDACIÓN",
      detail: "Una acción sugerida y acotada.",
      boundary: "QUÉ HACER DESPUÉS",
    },
  ],
  problemSignals: [
    {
      id: "P-CV-01",
      title: "La descripción del puesto se convierte en verdad del candidato.",
      detail: "Un requisito del empleador nunca debe convertirse en evidencia de que el candidato posee esa capacidad.",
    },
    {
      id: "P-CV-02",
      title: "Una reescritura eleva la responsabilidad.",
      detail: "Participó puede convertirse en lideró; implementó en diseñó; diseño en propiedad de arquitectura.",
    },
    {
      id: "P-CV-03",
      title: "Un único score oculta el camino de decisión.",
      detail: "Una decisión útil necesita evidencia, gaps, incertidumbre, elegibilidad y siguiente acción; no solamente un porcentaje.",
    },
  ],
  truthClasses: [
    ["CANDIDATE_ASSERTED", "el candidato afirma esto", "afirmación del lado de la fuente"],
    ["VERIFIED_FACT", "requiere evidencia/fuente", "hecho validado"],
    ["DERIVED_FACT", "requiere regla de derivación", "hecho calculado del lado del candidato"],
    ["REWRITE", "requiere afirmación fuente", "redacción que preserva el hecho"],
    ["SUGGESTION", "no puede convertirse directamente en ResumeClaim", "solo propuesta"],
  ] as const,
  matchExamples: [
    ["JavaScript", "Java", "GAP"],
    ["Azure", "AWS", "GAP"],
    ["2 años documentados", "5 años requeridos", "GAP"],
    ["colaboró", "liderar equipos de ingeniería", "GAP"],
    ["autorización laboral ausente", "autorización US requerida", "UNKNOWN"],
    ["evidencia TypeScript", "TypeScript requerido", "MATCH"],
  ] as const,
  escalationExamples: [
    ["participó", "lideró", "REQUIERE CONFIRMACIÓN"],
    ["implementó", "diseñó", "REQUIERE CONFIRMACIÓN"],
    ["diseñó", "arquitectó", "REQUIERE CONFIRMACIÓN"],
    ["construyó", "fue propietario de", "REQUIERE CONFIRMACIÓN"],
    ["construyó APIs", "desarrolló APIs", "EJEMPLO APROBADO"],
  ] as const,
  assessmentStates: [
    ["READY_NOW", "SÍ", "APPLY"],
    ["STRONG_STRETCH", "CONSIDERAR", "APPLY_WITH_CAUTION"],
    ["BUILDABLE", "AÚN_NO", "BUILD_FIRST"],
    ["ASPIRATIONAL", "OBJETIVO_FUTURO", "PLAN_PATH"],
    ["LOW_ALIGNMENT", "NO", "DEPRIORITIZE"],
  ] as const,
  providers: [
    ["GREENHOUSE", "boardToken + jobId"],
    ["LEVER", "site + postingId"],
    ["ASHBY", "jobBoardName + selector de URL de oferta alojada"],
  ] as const,
  providerRules: [
    "hosts de proveedor fijos",
    "solo HTTPS",
    "rechazo de redirects",
    "solo JSON",
    "timeout cancelable",
    "límite de respuesta de 2 MiB",
    "validación de identidad del proveedor",
    "sin fetch de URLs arbitrarias",
  ],
  unknownReasons: ["SOURCE_SILENT", "UNRECOGNIZED_SOURCE_VALUE", "INVALID_SOURCE_VALUE"],
  evidence: [
    ["E-CV-01", "Límite entre evidencia y afirmación profesional", "FUENTE VERIFICADA"],
    ["E-CV-02", "La verdad del puesto permanece del lado del puesto", "FUENTE VERIFICADA"],
    ["E-CV-03", "Matching de requisitos respaldado por evidencia", "FUENTE + ARTEFACTO DE PRUEBA"],
    ["E-CV-04", "Guardrails de escalamiento de responsabilidad", "FUENTE + ARTEFACTO DE PRUEBA"],
    ["E-CV-05", "Claim Ledger / procedencia del CV", "FUENTE VERIFICADA"],
    ["E-CV-06", "ResumeVersion direccionado por contenido", "FUENTE + ARTEFACTO DE PRUEBA"],
    ["E-CV-07", "Grafo durable Career Vault", "ARTEFACTO DE PRUEBA"],
    ["E-CV-08", "Evaluación de oportunidad", "FUENTE VERIFICADA"],
    ["E-CV-09", "Límite CAN / WANT de CareerTarget", "FUENTE VERIFICADA"],
    ["E-CV-10", "Límite entre estado de mercado y ocurrencia", "FUENTE VERIFICADA"],
    ["E-CV-11", "Adquisición controlada por proveedor", "FUENTE + ARTEFACTO DE PRUEBA"],
    ["E-CV-12", "Disciplina de estado derivado UNKNOWN", "FUENTE VERIFICADA"],
    ["E-CV-13", "Proyección Job Intelligence ligada a procedencia", "DOCUMENTADO COMPLETO"],
    ["E-CV-14", "Evaluación del JobSnapshot exacto de mercado", "FUENTE + ARTEFACTO DE PRUEBA"],
  ] as const,
  verification: [
    ["La verdad del candidato requiere procedencia", "FUENTE / PRUEBA", "E-CV-01"],
    ["RequirementMatch preserva GAP / UNKNOWN", "FUENTE / PRUEBA", "E-CV-03"],
    ["Se verifica el escalamiento de responsabilidad", "ARTEFACTO DE PRUEBA", "E-CV-04"],
    ["La redacción del CV traza a afirmaciones del candidato", "ARTEFACTO DE PRUEBA", "E-CV-06"],
    ["Career Vault rechaza contenido renderizado alterado", "ARTEFACTO DE PRUEBA", "E-CV-07"],
    ["La recomendación no es probabilidad del empleador", "LÍMITE DE FUENTE", "E-CV-08"],
    ["El ingreso de proveedores está acotado", "FUENTE / PRUEBA", "E-CV-11"],
    ["UNKNOWN de mercado es de primera clase", "FUENTE", "E-CV-12"],
    ["Se consume el JobSnapshot exacto del mercado", "FUENTE / PRUEBA", "E-CV-14"],
    ["Identidad de oportunidad / ciclo OPEN-CLOSED-STALE", "SIGUIENTE / NO DECLARADO", "M4B-07"],
  ] as const,
} as const;
