export const evidenceTranslationsEs = {
  "E-AP-01": {
    title: "Bloques de telemetría acotados",
    claim: "La adquisición en vivo se acumula en bloques de telemetría acotados antes de entrar a la ruta de persistencia durable.",
    context: "El controlador live crea un TelemetryBlockAssembler con una ventana de 5000 ms y envía los bloques codificados emitidos a través de la cola de commit ordenada.",
    limitations: "El código demuestra la elección de implementación de 5000 ms. No establece que esa duración sea universalmente óptima ni esté validada por benchmarks en todos los dispositivos.",
  },
  "E-AP-02": {
    title: "Codec BINARY_OBD2_V3",
    claim: "Un formato binario de telemetría versionado preserva resultados de adquisición más ricos e incluye metadata de integridad CRC.",
    context: "El codec se identifica como BINARY_OBD2_V3 / versión 3, codifica lecturas junto con respuestas negativas, fragmentos raw y frames, calcula CRC32 y valida magic/version/length al decodificar.",
    limitations: "La auditoría del portfolio verificó código y artefactos de prueba actuales, pero no volvió a ejecutar de forma independiente toda la suite de AutoPulse durante esta recuperación de evidencia.",
  },
  "E-AP-03": {
    title: "Contrato de integridad y secuencia de persistencia",
    claim: "La persistencia de telemetría distingue reintento válido, conflicto, saltos de secuencia, regresiones, truncamiento y corrupción CRC.",
    context: "El repositorio valida identidad de workspace/sesión, formato V3, longitud de bytes, CRC y secuencia antes de avanzar atómicamente los contadores de sesión junto con la inserción del bloque.",
    limitations: "Este registro respalda la semántica de persistencia a nivel de repositorio. Por sí solo no demuestra confiabilidad end-to-end de adquisición física.",
  },
  "E-AP-04": {
    title: "Commit ordenado y reintento acotado",
    claim: "Los commits de bloques de telemetría se serializan y únicamente las fallas de persistencia explícitamente transitorias reciben un reintento.",
    context: "La cola reintenta DATABASE_WRITE_FAILED y CONCURRENT_SESSION_UPDATE una vez, y deja de aceptar bloques adicionales después de una falla terminal de commit.",
    limitations: "Esta es una política de reintento deliberadamente estrecha, no una garantía general de que toda falla de base de datos pueda recuperarse automáticamente.",
  },
  "E-AP-05": {
    title: "Ciclo de vida explícito de sesión live",
    claim: "Una sesión de telemetría live posee estados explícitos de ciclo de vida en lugar de inferirse por si una pantalla de UI está abierta.",
    context: "El código actual modela los estados CREATED, PREPARING, ACTIVE, STOPPING, COMPLETED, INTERRUPTED y RECOVERABLE, y registra eventos de ciclo de vida.",
    limitations: "La evidencia respalda el contrato de ciclo de vida del repositorio, no todos los escenarios posibles del ciclo de vida del sistema operativo en cada dispositivo.",
  },
  "E-AP-06": {
    title: "Recuperación de sesiones huérfanas",
    claim: "La telemetría persistida puede utilizarse para reconciliar una sesión huérfana no terminal y registrar explícitamente una terminación inesperada de la aplicación.",
    context: "recoverOrphanedSessions() encuentra sesiones CREATED/PREPARING/ACTIVE/STOPPING, reconcilia contadores persistidos, marca la sesión como INTERRUPTED y registra UNEXPECTED_APP_TERMINATION.",
    limitations: "La recuperación hace explícita la interrupción; no afirma que la sesión huérfana terminara normalmente ni que toda falla externa de hardware sea recuperable.",
  },
  "E-AP-07": {
    title: "Comportamiento NO_DATA",
    claim: "NO_DATA se preserva como un resultado de adquisición distinto y NO_DATA repetidos pueden cambiar el conjunto activo de polling sin confundirse con fallas de transporte.",
    context: "Una adquisición exitosa reinicia el contador; tres resultados NO_DATA consecutivos retiran el PID y emiten PID_RETIRED_NO_DATA. TIMEOUT, ELM_ERROR y DISCONNECTED no usan la misma ruta de retiro.",
    limitations: "El umbral de retiro es comportamiento de la implementación actual y no debe generalizarse como requisito del estándar OBD.",
  },
  "E-AP-08": {
    title: "Resumen e integridad de sesión",
    claim: "La interpretación a nivel de sesión preserva si la telemetría subyacente está completa, parcial, degradada, corrupta o no disponible.",
    context: "El builder resume completitud de bloques, conteos de corrupción/no soporte, gaps, totales de eventos/lecturas y min/max/promedio/timestamps de señales, manteniendo la clasificación de integridad.",
    limitations: "Un resumen solo es tan completo como la telemetría persistida que puede leer; los estados no disponibles o corruptos permanecen visibles en lugar de sintetizarse.",
  },
  "E-AP-09": {
    title: "Superficies de producto live",
    claim: "El código actual incluye superficies de producto dedicadas para conexión, inicialización, sesión live, diagnósticos y flujos de resumen de sesión.",
    context: "El árbol fuente incluye ConnectObdScreen, InitializationScreen, LiveSessionScreen, SessionSummaryScreen y DiagnosticsLogScreen.",
    limitations: "La existencia de código fuente no es un artefacto de screenshot. La evidencia visual de producto debe provenir de un render o captura real del dispositivo antes de presentarse como tal.",
  },

  "E-CV-01": {
    title: "Límite de verdad entre evidencia y afirmaciones profesionales",
    claim: "La evidencia del candidato y sus afirmaciones se modelan como objetos separados con reglas explícitas de verdad y procedencia.",
    context: "CareerEvidence conserva identidad de fuente, extracto, locator y metadata de revisión, mientras CareerAssertion conserva una truth class y referencias a identidades de evidencia/fuente.",
    limitations: "Esto modela reglas de procedencia y validación; no implica que cada fuente importada sea automáticamente confirmada por el candidato u objetivamente verdadera.",
  },
  "E-CV-02": {
    title: "La verdad del puesto permanece del lado del puesto",
    claim: "Los requisitos del puesto derivan de descripciones de empleo y no pueden autorizar verdad sobre capacidades del candidato.",
    context: "JobRequirement está ligado a JobDescriptionId; JobSnapshot con procedencia de mercado lleva un límite explícito que indica que no es verdad del candidato.",
    limitations: "Un parser todavía puede extraer requisitos de forma imperfecta. Esta evidencia respalda el límite de dominio, no una corrección universal de extracción.",
  },
  "E-CV-03": {
    title: "Matching de requisitos respaldado por evidencia",
    claim: "El matching preserva los estados MATCH, POTENTIAL_MATCH, GAP, UNKNOWN y BLOCKER y referencia afirmaciones del candidato para matches positivos.",
    context: "Los fixtures de benchmark cubren skills, antigüedad, responsabilidades, educación, idioma, ubicación, autorización laboral, certificaciones, scoring y requisitos no catalogados en inglés y español.",
    limitations: "El artefacto de benchmark demuestra comportamientos controlados, no equivalencia con un ATS comercial ni corrección para toda descripción de puesto posible.",
  },
  "E-CV-04": {
    title: "Guardrails de escalamiento de responsabilidad",
    claim: "Las reescrituras de alto riesgo que elevan responsabilidad pueden detenerse para confirmación en lugar de entrar silenciosamente en la redacción aprobada del candidato.",
    context: "Los fixtures rechazan participación→liderazgo, implementación→diseño, diseño→propiedad de arquitectura y elevación no respaldada de ownership/impact, mientras permiten ejemplos controlados de redacción equivalente.",
    limitations: "Este es un guard semántico acotado con cobertura evaluada explícita; no debe describirse como prevención universal de alucinaciones ni prueba universal de entailment.",
  },
  "E-CV-05": {
    title: "Claim Ledger y procedencia de claims del CV",
    claim: "Los claims del CV deben apuntar a afirmaciones conocidas del candidato; las sugerencias no pueden convertirse directamente en ResumeClaims.",
    context: "Los claims canónicos comienzan con la redacción exacta de la afirmación; se espera que una redacción reescrita pase grounding antes de reemplazar la redacción canónica.",
    limitations: "La procedencia impide que claims desconocidos o sugeridos entren directamente al ledger, pero no elimina todos los posibles problemas semánticos de calidad en texto generado.",
  },
  "E-CV-06": {
    title: "Procedencia de ResumeVersion direccionada por contenido",
    claim: "Una versión aprobada de CV queda ligada a identidades de candidato/puesto/match/claim, SHA-256 de contenido y metadata del contrato de generación.",
    context: "Los artefactos de prueba cubren identidad determinista para el mismo contenido/objetivo aprobado, cambio de identidad cuando cambia el objetivo, procedencia de afirmaciones y rechazo de redacción materialmente no trazable.",
    limitations: "El direccionamiento por contenido demuestra relaciones de identidad/procedencia del artefacto; no garantiza que el CV produzca un resultado de contratación.",
  },
  "E-CV-07": {
    title: "Grafo durable Career Vault",
    claim: "Candidato, evidencia, afirmaciones, inteligencia del puesto, match y artefactos de CV pueden persistirse y validarse al recargar como un único grafo de procedencia.",
    context: "Los fixtures cubren integridad al recargar, reutilización de historial inmutable, historial separado por objetivo, rechazo de manifiesto antes de guardar, rechazo de documento alterado y configuración durable fail-closed.",
    limitations: "El artefacto de prueba valida el grafo de persistencia modelado; no es un SLA de disponibilidad en producción ni prueba de escala ilimitada de persistencia.",
  },
  "E-CV-08": {
    title: "Evaluación de oportunidad antes de aplicar",
    claim: "Un match respaldado por evidencia puede convertirse en una recomendación acotada de aplicación sin afirmar probabilidad del empleador.",
    context: "La decisión derivada contiene recommendation, shouldApply, nextAction, eligibility, evidence strength, coverage, supporting evidence, gaps e incertidumbres.",
    limitations: "La fuente dice explícitamente que esto no es probabilidad de contratación, decisión del recruiter, probabilidad de entrevista ni score de ATS comercial.",
  },
  "E-CV-09": {
    title: "Intención CareerTarget separada de capacidad",
    claim: "La intención del candidato puede afectar relevancia/priorización de objetivos, pero no puede satisfacer un JobRequirement ni crear CareerEvidence.",
    context: "El dominio modela explícitamente CareerTarget como dirección estratégica propiedad del candidato: CAN y WANT permanecen como entradas diferentes.",
    limitations: "La relevancia del objetivo es relevancia estratégica, no nueva evidencia de capacidad ni garantía de fit para un empleador.",
  },
  "E-CV-10": {
    title: "Estado semántico de mercado vs ocurrencia de observación",
    claim: "El contenido semántico observado desde una fuente de mercado es distinto del evento temporal de volver a observar ese mismo contenido.",
    context: "MarketObservation conserva hechos raw/explícitos de fuente; ObservationOccurrence registra el momento de observación sin cambiar la identidad semántica del mercado.",
    limitations: "Esto es historial durable de observación, no identidad lógica completa de oportunidad, deduplicación ni semántica de ciclo OPEN/CLOSED.",
  },
  "E-CV-11": {
    title: "Adquisición controlada por proveedor",
    claim: "Ofertas seleccionadas de Greenhouse, Lever y Ashby pueden entrar mediante adaptadores acotados específicos por proveedor sin fetch arbitrario de URLs.",
    context: "Los adaptadores construyen endpoints fijos de proveedor, exigen HTTPS/JSON, rechazan redirects, limitan tamaño/tiempo de respuesta y mapean únicamente campos explícitos de la fuente.",
    limitations: "El runtime es intencionalmente una oferta a la vez y disparado manualmente. No es crawler, poller continuo de proveedores ni worker amplio de sincronización.",
  },
  "E-CV-12": {
    title: "UNKNOWN como estado derivado de primera clase",
    claim: "Los campos de mercado derivados permanecen UNKNOWN con una razón explícita cuando el material fuente no autoriza un valor.",
    context: "Las razones UNKNOWN incluyen SOURCE_SILENT, UNRECOGNIZED_SOURCE_VALUE e INVALID_SOURCE_VALUE; los campos conocidos conservan evidencia de fuente y un tipo de derivación controlado.",
    limitations: "Esta evidencia describe los límites deterministas actuales de interpretación de mercado, no todos los métodos de inferencia futuros que CV Engine pueda añadir.",
  },
  "E-CV-13": {
    title: "Proyección Job Intelligence ligada a procedencia",
    claim: "Solo texto fuente autorizado puede cruzar desde la verdad de mercado hacia Job Intelligence, y la metadata de mercado no se sintetiza como texto de requisitos.",
    context: "La entrada legal del parser es texto raw TEXT exacto de la observación o la descripción explícita exacta desde evidencia JSON/proveedor; una descripción JSON explícita ausente falla de forma cerrada.",
    limitations: "Este bridge controla la entrada autorizada al parser y su procedencia; no afirma que el parsing posterior de requisitos sea universalmente correcto.",
  },
  "E-CV-14": {
    title: "Integración de evaluación con el JobSnapshot exacto de mercado",
    claim: "Market Application Intelligence consume el JobSnapshot durable exacto con procedencia de mercado en lugar de reconstruir la verdad del puesto al momento de evaluar.",
    context: "La ruta selecciona JobSnapshotId, el matching lee el conjunto almacenado de requisitos y OpportunityHistory preserva la identidad/procedencia exacta del snapshot.",
    limitations: "M4B-07 sobre identidad/ciclo de oportunidad sigue pendiente: deduplicación entre fuentes, OPEN/CLOSED/STALE y semántica de freshness no se declaran completas.",
  },

  "E-PRO-01": {
    title: "Modelo espacial que preserva jerarquía",
    claim: "Un sistema profesional de mapeo de infraestructura preserva la jerarquía física mientras deriva vistas espaciales navegables desde datos en lugar de coordenadas fijas de pantalla.",
    context: "La implementación revisada modela infraestructura mediante relaciones explícitas de sitio, estructura, nivel, sala, posición y equipo. La ubicación espacial se deriva de dimensiones físicas y reglas de grid para conservar contexto operativo en lugar de aplanar la instalación en pantallas desconectadas.",
    limitations: "Este registro abstrae intencionalmente empleador/cliente, repositorio, nombres de instalaciones, rutas fuente, screenshots y datos operativos. Demuestra el patrón de arquitectura revisado, no propiedad del sistema profesional completo ni resultados de rendimiento.",
  },
  "E-PRO-02": {
    title: "Implementación a través de vistas operativas",
    claim: "Eduardo contribuyó a la implementación de contexto de equipos respaldado por persistencia, comportamiento de provisioning, vistas de dispositivos/telemetría y navegación operativa en un sistema profesional real.",
    context: "La historia profesional privada revisada para este portfolio contiene cambios de implementación de autoría en persistencia de datos, lógica de provisioning, presentación de dispositivos, contexto de telemetría/power-path y vistas de infraestructura relacionadas. El registro público mantiene explícito el límite de responsabilidad sin exponer activos del empleador.",
    limitations: "La evidencia respalda responsabilidad de implementación contribuida. No afirma autoría exclusiva, ownership de producto, resultados del cliente, escala de deployment ni métricas que no sean publicables y respaldadas de forma independiente.",
  },
  "E-PRO-03": {
    title: "Hardening de seguridad basado en roles y QA",
    claim: "Comportamiento basado en roles, contención de seguridad y QA de seguridad fueron partes explícitas del trabajo profesional de implementación de Eduardo y no afirmaciones decorativas del portfolio.",
    context: "El historial profesional revisado incluye implementación relacionada con roles, trabajo de contención de seguridad no disruptiva y un reporte de QA de seguridad. Eso establece el hardening de seguridad como parte de la responsabilidad de ingeniería representada aquí.",
    limitations: "El portfolio público no expone el reporte privado de seguridad, vulnerabilidades, detalles de remediación, coordenadas del repositorio ni topología del cliente. Este registro no es una certificación ni una afirmación de cobertura exhaustiva de seguridad.",
  },
  "E-GP-01": {
    title: "Ruta full stack del navegador a los datos",
    claim: "GPets contiene una ruta inspeccionable navegador→API→servicio→persistencia, en lugar de ser un artefacto solo frontend o solo backend.",
    context: "El navegador inicializa configuración de producto e interacción de mapa, llama APIs autenticadas de incidentes y recibe datos de dominio que el servicio Spring persiste en Firebase Realtime Database. El mismo repositorio expone así superficie de producto, límite HTTP, servicio de aplicación y ruta de datos.",
    limitations: "Esta es evidencia a nivel de código de una implementación archivada de reto técnico. No afirma tráfico de producción, SLA operativo, disponibilidad actual del deployment ni adopción comercial.",
  },
  "E-GP-02": {
    title: "Límite de API autenticada",
    claim: "Las solicitudes protegidas de la API de GPets se verifican en servidor contra bearer tokens de Firebase antes de que los handlers de aplicación reciban contexto de identidad autenticada.",
    context: "El navegador obtiene un Firebase ID token después de iniciar sesión con Google. El OncePerRequestFilter de Spring verifica bearer tokens y rechaza autorización ausente o inválida para rutas API protegidas, pasando atributos de identidad decodificados a la solicitud.",
    limitations: "Este registro demuestra el límite de autenticación implementado visible en código. No es un penetration test independiente, un threat model formal ni una afirmación de que toda preocupación de autorización esté resuelta exhaustivamente.",
  },
  "E-GP-03": {
    title: "Loop de persistencia y broadcast en tiempo real",
    claim: "Un incidente guardado se persiste mediante el backend y luego se publica en un tópico STOMP al que clientes conectados del navegador se suscriben y reconcilian en su vista actual.",
    context: "Después de completar correctamente la persistencia en Firebase, el servicio publica el incidente en /topic/incidents. El navegador conecta mediante SockJS/STOMP, se suscribe al tópico, actualiza su colección de incidentes y vuelve a renderizar el estado relevante de mapa/feed.",
    limitations: "El código demuestra la ruta de aplicación en tiempo real y la estrategia de reconexión presente en el repositorio. No establece escala multi-región, semántica de entrega garantizada ni latencia benchmarkeada.",
  },
  "E-GP-04": {
    title: "Cola offline con límite de replay idempotente",
    claim: "GPets encola escrituras del navegador en IndexedDB para sincronización posterior y acompaña escrituras reproducidas con claves de idempotencia que el backend cachea para reducir efectos duplicados.",
    context: "El navegador almacena mutaciones pendientes en una cola de sincronización IndexedDB, asigna un Idempotency-Key y reintenta solicitudes encoladas cuando vuelve la conectividad. El backend almacena claves procesadas en Redis con TTL acotado y puede devolver el resultado cacheado para una clave repetida.",
    limitations: "El mecanismo reduce efectos duplicados para el límite de solicitud implementado; no es una garantía general de exactly-once ni demuestra todos los modos de falla de un sistema distribuido offline.",
  },
} as const;

export const sourceLabelTranslationsEs: Record<string, string> = {
  "BinaryObd2V3Codec tests": "Pruebas de BinaryObd2V3Codec",
  "TelemetryBlockRepository tests": "Pruebas de TelemetryBlockRepository",
  "Orphan recovery integration test": "Prueba de integración de recuperación de huérfanas",
  "RealTelemetryPoller tests": "Pruebas de RealTelemetryPoller",
  "SessionSummaryBuilder tests": "Pruebas de SessionSummaryBuilder",
  "Live screens source directory": "Directorio fuente de pantallas live",
  "Match benchmark": "Benchmark de matching",
  "Semantic entailment tests": "Pruebas de entailment semántico",
  "Resume versioning tests": "Pruebas de versionado de CV",
  "Career Vault tests": "Pruebas de Career Vault",
  "Market architecture execution record": "Registro de ejecución de arquitectura de mercado",
  "Controlled provider adapters": "Adaptadores controlados de proveedores",
  "Controlled source acquisition tests": "Pruebas de adquisición controlada de fuentes",
  "M4B-05 execution record": "Registro de ejecución M4B-05",
  "M4B-06 execution record": "Registro de ejecución M4B-06",
  "Market assessment integration tests": "Pruebas de integración de evaluación de mercado",
  "Private professional architecture source": "Fuente privada de arquitectura profesional",
  "Private professional implementation history": "Historial privado de implementación profesional",
  "Private professional security and QA history": "Historial privado de seguridad y QA profesional",
  "Browser application": "Aplicación del navegador",
  "Incident REST controller": "Controller REST de incidentes",
  "Incident service and persistence": "Servicio de incidentes y persistencia",
  "Firebase authentication filter": "Filtro de autenticación Firebase",
  "Browser authentication flow": "Flujo de autenticación del navegador",
  "Incident service and realtime publisher": "Servicio de incidentes y publisher en tiempo real",
  "Browser STOMP subscriber": "Suscriptor STOMP del navegador",
  "Browser offline synchronization manager": "Gestor de sincronización offline del navegador",
  "Backend idempotency service": "Servicio backend de idempotencia",
  "Idempotent incident write boundary": "Límite idempotente de escritura de incidentes",
};

export const privateProfessionalSourceNoteEs =
  "Revisado contra material fuente profesional privado. Repositorio, ruta, coordenadas de revisión, identidad del cliente e identificadores operativos se ocultan intencionalmente del portfolio público.";
