import Image from 'next/image';
import Link from 'next/link';
import { CoreFallback } from '@/components/scene/core-fallback';
import { SystemArtifact } from '@/components/systems/system-artifact';
import { Conversation } from '@/components/content/conversation';
import { featuredSystems } from '@/content/systems/index';
import { publicNotes } from '@/content/notes';
import { profile } from '@/content/profile';
import { problemPaths, capabilities, workingModel } from '@/content/capabilities';
import { professional } from '@/content/professional';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Eduardo Merino — Software Systems & Applied AI', profile.proposition, '/');
const featuredNotes = [publicNotes[0], publicNotes[2], publicNotes[3]];
export default function Home() {
  return <main id="main-content" tabIndex={-1}>
    <section className="hero container">
      <div className="hero-copy enter"><p className="eyebrow hero-identity"><span className="identity-line" aria-hidden="true"/>Eduardo Merino <span>/</span> Software systems builder</p><h1><span className="hero-line"><span className="hero-mobile-break">Complex</span><span> problems.</span></span><span className="hero-line hero-line-accent"><span className="hero-mobile-break">Working</span><span> systems.</span></span></h1><p className="hero-statement">{profile.proposition}</p><p className="hero-scope">{profile.scope}</p><div className="actions"><Link href="/systems" className="button primary">Explore systems <span aria-hidden="true">↗</span></Link><Link href="/contact" className="hero-secondary">Start a conversation <span aria-hidden="true">↗</span></Link></div></div>
      <div className="hero-art"><div className="core-stage" data-scene-slot="HOME"><CoreFallback/></div><div className="core-caption"><span className="eyebrow">Structure from complexity</span><span className="core-caption-index" aria-hidden="true">01 — 03</span></div></div>
      <div className="hero-bottom"><span>Full-stack engineering · Applied AI · Real-world systems</span><a href="#problems">A closer look <span aria-hidden="true">↓</span></a></div>
    </section>
    <section className="problem-section section rule-top" id="problems"><div className="container"><div className="section-head"><div><p className="eyebrow accent">01 / Start with your situation</p><h2>What needs to<br/>work better?</h2></div><p>You don’t need a technical brief to start. A problem, an idea or a workflow that keeps getting in the way is enough.</p></div><div className="problem-paths">{problemPaths.map((path,i)=><details key={path.id} className="problem-path"><summary><span className="eyebrow">0{i+1}</span><h3>{path.title}</h3><span className="expand-symbol" aria-hidden="true">+</span><span className="path-teaser">{path.summary}</span></summary><div className="problem-detail"><p>{path.detail}</p><Link href={`/contact?intent=${path.id}`} className="text-link">Talk about this <span aria-hidden="true">↗</span></Link></div></details>)}</div><details className="capabilities-disclosure"><summary>Where I can contribute <span aria-hidden="true">+</span></summary><div className="capability-list">{capabilities.map(item=><Link href={item.href} key={item.title}><h3>{item.title}</h3><p>{item.description}</p><span aria-hidden="true">↗</span></Link>)}</div></details></div></section>
    <section className="selected-section section container" id="selected-systems"><div className="section-head"><div><p className="eyebrow accent">02 / Selected systems</p><h2>Different problems.<br/>A builder’s approach.</h2></div><p>From a vehicle’s signals to a territory’s constraints to an editorial workflow. See the problem, the system and the reasoning underneath.</p></div>{featuredSystems.map((system,i)=><article key={system.slug} className={`system-encounter encounter-${i}`} data-accent={system.accent}><div className="encounter-copy"><p className="eyebrow accent"><span className="encounter-number">0{i+1}</span>{system.category}</p><h3><Link href={`/systems/${system.slug}`}>{system.name}</Link></h3><p className="encounter-summary">{system.summary}</p><p className="encounter-built">{system.built}</p><div className="encounter-state"><span className="state-line" aria-hidden="true"/>{system.state.label}</div><Link href={`/systems/${system.slug}`} className="text-link">Explore {system.name}<span aria-hidden="true">↗</span></Link></div><SystemArtifact system={system}/></article>)}<div className="all-systems-row"><p>More product work, professional contributions and experiments.</p><Link href="/systems" className="text-link">All systems <span aria-hidden="true">↗</span></Link></div></section>
    <section className="professional-section section"><div className="container split"><div><p className="eyebrow accent">03 / Professional reality</p><h2>{professional.title}</h2></div><div className="professional-copy"><p className="lead">{professional.summary}</p><ul className="proof-areas">{professional.areas.map(area=><li key={area}>{area}</li>)}</ul><Link href={professional.href} className="text-link">Explore the professional record <span aria-hidden="true">↗</span></Link><p className="boundary-caption">{professional.boundary}</p></div></div></section>
    <section className="method-section section container"><div className="section-head"><div><p className="eyebrow accent">04 / How I work</p><h2>Make the problem clear.<br/>Then make it work.</h2></div><p>A connected path from understanding the situation to checking what the software actually does.</p></div><ol className="working-model">{workingModel.map((step,i)=><li key={step.title}><span className="eyebrow">0{i+1}</span><h3>{step.title}</h3><p>{step.detail}</p></li>)}</ol><div className="method-proof"><p>There is evidence underneath the presentation.</p><Link href="/evidence" className="text-link">Inspect the proof <span aria-hidden="true">↗</span></Link></div></section>
    <section className="paper section"><div className="container"><div className="section-head"><div><p className="eyebrow">05 / Engineering notes</p><h2>Ideas from<br/>inside the work.</h2></div><p>Short, enduring lessons about data, decisions and the boundaries that make software dependable.</p></div><div className="featured-notes">{featuredNotes.map((note,i)=><article key={note.slug}><span className="eyebrow">0{i+1} / {note.territory}</span><h3><Link href={`/notes/${note.slug}`}>{note.title}</Link></h3><p>{note.thesis}</p><Link href={`/notes/${note.slug}`} className="text-link" aria-label={`Read ${note.title}`}>Read note <span aria-hidden="true">↗</span></Link></article>)}</div><Link href="/notes" className="text-link notes-more">Open the notebook <span aria-hidden="true">↗</span></Link></div></section>
    <section className="human-section section container"><div className="human-portrait"><Image src={profile.portrait} alt="Eduardo Merino" width={480} height={594} sizes="(max-width: 767px) 50vw, 300px"/></div><div className="human-copy"><p className="eyebrow accent">06 / The person behind the work</p><h2>Hi, I’m Eduardo.</h2><p className="lead">I like the part where a difficult, real-world problem starts to become understandable — and the work of turning that understanding into software people can use.</p><Link href="/about" className="text-link">Meet the builder <span aria-hidden="true">↗</span></Link></div></section>
    <div className="rule-top"><Conversation/></div>
  </main>;
}
