import Link from 'next/link';
import { systemCases, featuredSystems } from '@/content/systems/index';
import { SystemArtifact } from '@/components/systems/system-artifact';
import { Conversation } from '@/components/content/conversation';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Systems', 'Eight documented software systems spanning selected flagships, professional contribution, active R&D and supporting work by Eduardo Merino.', '/systems');
export default function SystemsPage() {
  return <main id="main-content" tabIndex={-1}><header className="page-intro container"><p className="eyebrow accent">The work</p><h1>Systems with a reason to exist.</h1><p className="lead">Real problems, deliberate decisions and an honest view of what has been built.</p><p className="system-count-signal">{featuredSystems.length} selected systems · {systemCases.length} documented systems</p></header><section className="container" aria-label="Selected systems">{featuredSystems.map((system,i)=><article className={`system-encounter encounter-${i}`} key={system.slug} data-accent={system.accent}><div className="encounter-copy"><p className="eyebrow accent">{system.category}</p><h2>{system.name}</h2><p className="encounter-summary">{system.summary}</p><p className="encounter-built">{system.built}</p><p className="encounter-state">{system.state.label}</p><Link className="text-link" href={`/systems/${system.slug}`}>Explore {system.name}<span aria-hidden="true">↗</span></Link></div><SystemArtifact system={system}/></article>)}</section><section className="section container"><div className="section-head"><div><p className="eyebrow accent">Further inside the room</p><h2>More ways of<br/>making things work.</h2></div><p>Professional contributions, new product directions and earlier full-stack work. Their stage and evidence boundaries stay visible.</p></div><div className="supporting-systems">{systemCases.filter(s=>s.placement!=='FLAGSHIP').map(system=><Link href={`/systems/${system.slug}`} key={system.slug}><span className="eyebrow">{system.placement === 'R&D' ? 'In development' : system.placement.toLowerCase()}</span><div><h3>{system.name}</h3><p>{system.summary}</p><span className="support-state">{system.state.label}</span></div><span className="row-arrow" aria-hidden="true">↗</span></Link>)}</div></section><div className="rule-top"><Conversation/></div></main>;
}
