import type { EvidenceRecord } from "@/lib/content/types";
const paRef = "002177e90431d6009498a88cc6eb20efc46e14b3";
const fsRef = "3640244fb12aabf818b002399f3b7cc28fbde14c";
export const currentEvidence: readonly EvidenceRecord[] = [
  { id: "E-PA-01", slug: "e-pa-01", systemId: "06", systemName: "prodAgentic", title: "A bounded, certified planning baseline", type: "TEST", state: "TEST_ARTIFACT", publicability: "PUBLIC", claim: "The published MK1 S2 ledger binds backend, frontend and browser verification to a fixed product-code revision.",
    sources: [{ label: "MK1 implementation and certification ledger", access: "PUBLIC_GITHUB", repository: "Em3rc0d/prodAgentic", path: "mk1/STATUS.md", ref: "abae59fd9815d27a4fb6e3caaeac953618dd3364", reviewedBlobSha: "c8a3a7289188e9681a356aecc3e53b8bf8b5da6e" }],
    context: "The inspected ledger identifies the S0–S2 product baseline and its post-merge CI run. Its operator path covers accepted ProfileVersion, batch planning, Editorial Memory, novelty/diversity and frozen planning evidence.", limitations: "This portfolio inspected published certification records; it did not rerun the project suite. Later S3/S4 certificates are recorded in that ledger but outside this planning case study. External publishing, commercial readiness and customer outcomes are not established by this record.", relatedDecisionIds: ["Version-bound planning"], relatedArchitectureIds: ["ProfileVersion", "ContentPlanV1"] },
  { id: "E-PA-02", slug: "e-pa-02", systemId: "06", systemName: "prodAgentic", title: "Editorial memory with explicit product boundaries", type: "ARCHITECTURE", state: "SOURCE_VERIFIED", publicability: "PUBLIC", claim: "The architecture separates domain/application responsibilities and preserves human acceptance and versioned planning context.",
    sources: [{ label: "MK1 system architecture", access: "PUBLIC_GITHUB", repository: "Em3rc0d/prodAgentic", path: "mk1/arch/SYSTEM_ARCHITECTURE.md", ref: paRef, reviewedBlobSha: "143db5d099ae0daaae601f0ccf98c6ac2f172cc6" }],
    context: "Next.js, FastAPI and MongoDB support a product whose plans retain their ProfileVersion. Architectural later-stage agents and workers are explicitly broader than the certified S2 behavior.", limitations: "An architecture contract documents responsibilities; it does not verify implementation of every future node. Refer to the exact S2 boundary before interpreting this diagram as current capability.", relatedDecisionIds: ["Explicit acceptance"], relatedArchitectureIds: ["Domain", "Application", "Infrastructure"] },
  { id: "E-FS-01", slug: "e-fs-01", systemId: "07", systemName: "FinanceSensor", title: "Evidence does not automatically become a transaction", type: "IMPLEMENTATION", state: "SOURCE_VERIFIED", publicability: "SANITIZED", claim: "The inspected Alpha.2 Dart runtime distinguishes normalized observations, confirmed canonical pairs and unresolved review/conflict outcomes.",
    sources: [{ label: "Alpha.2 canonical runtime", access: "PUBLIC_GITHUB", repository: "Em3rc0d/FinanceSensor", path: "spikes/mobile-shell/lib/alpha2/alpha2_runtime.dart", ref: fsRef, reviewedBlobSha: "56dcad9c1f40cb90f684ad061317b78f59b77bb3" }],
    context: "The code normalizes and orders evidence, rejects duplicate evidence identities, reconciles confirmed pairs and blocks unresolved materialization. This supports a source-level claim about the implemented algorithm boundary.", limitations: "Source inspection is not execution, physical Gmail proof, parser coverage, mobile vault validation or a release certificate. Real financial data and secrets are not included in this record.", relatedDecisionIds: ["Observation versus transaction"], relatedArchitectureIds: ["Alpha2RuntimeResult"] },
];
