import type { EvidenceRecord } from "@/lib/content/types";

const repository = "Em3rc0d/harvard-ats-resume";
const ref = "develop";

export const cvEngineEvidenceRecords: readonly EvidenceRecord[] = [
  {
    id: "E-CV-01",
    slug: "e-cv-01",
    systemId: "02",
    systemName: "CV Engine",
    title: "Career evidence and assertion truth boundary",
    type: "MODEL",
    claim: "Candidate evidence and candidate assertions are modeled as separate objects with explicit truth/provenance rules.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "CareerEvidence", repository, path: "lib/domain/candidate/CareerEvidence.ts", ref, reviewedBlobSha: "01d802ef9cdaa2234b484a6d3f6588fb614676e5" },
      { label: "CareerAssertion", repository, path: "lib/domain/candidate/CareerAssertion.ts", ref, reviewedBlobSha: "422d0b25c8c508abef0be25f8538376583aa2351" },
      { label: "Truth classes", repository, path: "lib/domain/shared/truth.ts", ref, reviewedBlobSha: "1e68cc211fb90ef5f138068874a5d73e8dd4faaf" },
    ],
    publicability: "PUBLIC",
    context: "CareerEvidence carries source identity, excerpt, locator/review metadata, while CareerAssertion carries a truth class and references evidence/source identities.",
    limitations: "This models provenance and validation rules; it does not imply every imported source is automatically candidate-confirmed or objectively true.",
    relatedDecisionIds: ["D-CV-01"],
    relatedArchitectureIds: ["career-evidence", "career-assertion"],
  },
  {
    id: "E-CV-02",
    slug: "e-cv-02",
    systemId: "02",
    systemName: "CV Engine",
    title: "Job truth remains job-side",
    type: "MODEL",
    claim: "Job requirements derive from job descriptions and cannot authorize candidate capability truth.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "JobRequirement", repository, path: "lib/domain/job/JobRequirement.ts", ref, reviewedBlobSha: "c5e1b88533558a3f8fa9ecca194583abcb1f5b69" },
      { label: "JobSnapshot", repository, path: "lib/domain/job/JobSnapshot.ts", ref, reviewedBlobSha: "ea5bc1732a3516bc4b663b518aa72f7e97be3a86" },
    ],
    publicability: "PUBLIC",
    context: "JobRequirement is bound to JobDescriptionId; market-provenanced JobSnapshot carries an explicit scope boundary that it is not candidate truth.",
    limitations: "A parser can still be imperfect at extracting job requirements. This evidence supports the domain boundary, not universal extraction correctness.",
    relatedDecisionIds: ["D-CV-01"],
    relatedArchitectureIds: ["job-requirement", "job-snapshot"],
  },
  {
    id: "E-CV-03",
    slug: "e-cv-03",
    systemId: "02",
    systemName: "CV Engine",
    title: "Evidence-backed requirement matching",
    type: "IMPLEMENTATION",
    claim: "Requirement matching preserves MATCH, POTENTIAL_MATCH, GAP, UNKNOWN and BLOCKER states and references candidate assertions for positive matches.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "RequirementMatch", repository, path: "lib/domain/matching/RequirementMatch.ts", ref, reviewedBlobSha: "ad1a7fae2b3ea7b50a0fae7531f5fbd69ed31712" },
      { label: "JobMatchEngine", repository, path: "lib/application/matching/JobMatchEngine.ts", ref },
      { label: "Match benchmark", repository, path: "tests/ats2/match-benchmark.test.ts", ref, reviewedBlobSha: "a90ac88e4bc908d41ce79d74b2fa8218508a610a" },
    ],
    publicability: "PUBLIC",
    context: "Benchmark fixtures cover skills, tenure, responsibilities, education, language, location, work authorization, certification, scoring and uncatalogued requirements in English/Spanish.",
    limitations: "The benchmark artifact demonstrates controlled behaviors, not equivalence to a commercial ATS or correctness for every possible job description.",
    relatedDecisionIds: ["D-CV-02"],
    relatedArchitectureIds: ["requirement-match"],
  },
  {
    id: "E-CV-04",
    slug: "e-cv-04",
    systemId: "02",
    systemName: "CV Engine",
    title: "Responsibility escalation guardrails",
    type: "TEST",
    claim: "High-risk rewrites that escalate responsibility can be held for confirmation instead of silently entering approved candidate wording.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "GroundingValidator", repository, path: "lib/application/grounding/GroundingValidator.ts", ref, reviewedBlobSha: "d3a0d46d120f293df88383d57409e76c00101518" },
      { label: "Semantic entailment tests", repository, path: "tests/ats2/semantic-entailment.test.ts", ref, reviewedBlobSha: "41b4a1986ecb2ecd642a9e2f780286b66305b139" },
    ],
    publicability: "PUBLIC",
    context: "Fixtures reject participation→leadership, implementation→design, design→architecture ownership and unsupported ownership/impact escalation while allowing controlled equivalent wording examples.",
    limitations: "This is a bounded semantic guard with explicit evaluated coverage; it must not be described as universal hallucination prevention or universal entailment proof.",
    relatedDecisionIds: ["D-CV-03"],
    relatedArchitectureIds: ["grounding"],
  },
  {
    id: "E-CV-05",
    slug: "e-cv-05",
    systemId: "02",
    systemName: "CV Engine",
    title: "Claim Ledger and resume claim provenance",
    type: "ARCHITECTURE",
    claim: "Resume claims must point back to known candidate assertions; suggestions cannot become resume claims directly.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "ClaimLedger", repository, path: "lib/domain/resume/ClaimLedger.ts", ref, reviewedBlobSha: "1d013d88a9199dcd100f1e65c047d4a6bc681cd2" },
      { label: "ResumeClaim", repository, path: "lib/domain/resume/ResumeClaim.ts", ref, reviewedBlobSha: "83dc74f9f1b3548a786af09d1cc90f27b8a78eb9" },
    ],
    publicability: "PUBLIC",
    context: "Canonical claims begin with exact assertion wording; rewritten wording is expected to pass grounding before replacing canonical wording.",
    limitations: "Provenance prevents unknown/suggestion claims from entering the ledger directly but does not eliminate every possible semantic quality problem in generated prose.",
    relatedDecisionIds: ["D-CV-03"],
    relatedArchitectureIds: ["claim-ledger", "resume-claim"],
  },
  {
    id: "E-CV-06",
    slug: "e-cv-06",
    systemId: "02",
    systemName: "CV Engine",
    title: "Content-addressed ResumeVersion provenance",
    type: "IMPLEMENTATION",
    claim: "An approved resume version is bound to candidate/job/match/claim identities, content SHA-256 and generation contract metadata.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "ResumeVersion", repository, path: "lib/domain/resume/ResumeVersion.ts", ref, reviewedBlobSha: "68a8a92d8b250a7aef1e9b7a308444dfe543e75d" },
      { label: "Resume versioning tests", repository, path: "tests/ats2/resume-versioning.test.ts", ref, reviewedBlobSha: "f402107f1ae7d90a561c4c2c7ec436d806a60a25" },
    ],
    publicability: "PUBLIC",
    context: "Test artifacts cover deterministic identity for same approved content/target, changed identity when target changes, assertion provenance and rejection of materially untraceable wording.",
    limitations: "Content addressing proves artifact identity/provenance relationships; it is not a guarantee that the resume will produce a hiring outcome.",
    relatedDecisionIds: ["D-CV-03"],
    relatedArchitectureIds: ["resume-version"],
  },
  {
    id: "E-CV-07",
    slug: "e-cv-07",
    systemId: "02",
    systemName: "CV Engine",
    title: "Durable Career Vault graph",
    type: "ARCHITECTURE",
    claim: "Candidate, evidence, assertions, job intelligence, match and resume artifacts can be persisted and reload-validated as one provenance graph.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "Career Vault tests", repository, path: "tests/ats2/career-vault.test.ts", ref, reviewedBlobSha: "80721b95f44ecf9872eda9a193c0acf01a7e752f" },
    ],
    publicability: "PUBLIC",
    context: "Fixtures cover reload integrity, immutable history reuse, separate target history, pre-save manifest rejection, tampered document rejection and fail-closed durable configuration.",
    limitations: "The test artifact validates the modeled persistence graph; it is not a production-availability SLA or proof of unlimited persistence scale.",
    relatedDecisionIds: ["D-CV-04"],
    relatedArchitectureIds: ["career-vault"],
  },
  {
    id: "E-CV-08",
    slug: "e-cv-08",
    systemId: "02",
    systemName: "CV Engine",
    title: "Opportunity assessment before application",
    type: "MODEL",
    claim: "An evidence-backed match can be converted into a bounded application recommendation without claiming employer probability.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "OpportunityAssessment", repository, path: "lib/application/opportunity/OpportunityAssessment.ts", ref, reviewedBlobSha: "4bc5641d17997750b34507ff06789792b84b41f5" },
      { label: "Market architecture execution record", repository, path: "docs/market-v0.1/README.md", ref, reviewedBlobSha: "0a3fa1eca27fd0c49f9537b636cdb2f8f7903120" },
    ],
    publicability: "PUBLIC",
    context: "The derived decision contains recommendation, shouldApply, nextAction, eligibility, evidence strength, coverage, supporting evidence, gaps and uncertainties.",
    limitations: "The source explicitly says this is not hiring probability, recruiter decision, interview probability or a commercial ATS score.",
    relatedDecisionIds: ["D-CV-05"],
    relatedArchitectureIds: ["opportunity-assessment"],
  },
  {
    id: "E-CV-09",
    slug: "e-cv-09",
    systemId: "02",
    systemName: "CV Engine",
    title: "CareerTarget intent separated from capability",
    type: "MODEL",
    claim: "Candidate intent may affect target relevance/prioritization but cannot satisfy a JobRequirement or create CareerEvidence.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "CareerTarget", repository, path: "lib/domain/candidate/CareerTarget.ts", ref, reviewedBlobSha: "7627f208e31aba7accf4333aa4069b39fdc77230" },
    ],
    publicability: "PUBLIC",
    context: "The domain explicitly models CareerTarget as candidate-owned strategic direction: CAN and WANT remain different inputs.",
    limitations: "Target relevance is strategic relevance, not new capability evidence and not an employer fit guarantee.",
    relatedDecisionIds: ["D-CV-06"],
    relatedArchitectureIds: ["career-target"],
  },
  {
    id: "E-CV-10",
    slug: "e-cv-10",
    systemId: "02",
    systemName: "CV Engine",
    title: "Market semantic state vs observation occurrence",
    type: "MODEL",
    claim: "The semantic content observed from a market source is distinct from the temporal event that the same content was observed again.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "MarketObservation", repository, path: "lib/domain/market/MarketObservation.ts", ref, reviewedBlobSha: "dd4202850bc97a2e1f79cb553d4352ddc90182d6" },
      { label: "ObservationOccurrence", repository, path: "lib/domain/market/ObservationOccurrence.ts", ref, reviewedBlobSha: "a245f0dbdd52bd99fd44e80f75799f96a5f39be9" },
    ],
    publicability: "PUBLIC",
    context: "MarketObservation holds raw/source-explicit facts; ObservationOccurrence records observation time without changing semantic market identity.",
    limitations: "This is durable observation history, not completed logical opportunity identity, deduplication or OPEN/CLOSED lifecycle semantics.",
    relatedDecisionIds: ["D-CV-07"],
    relatedArchitectureIds: ["market-observation", "observation-occurrence"],
  },
  {
    id: "E-CV-11",
    slug: "e-cv-11",
    systemId: "02",
    systemName: "CV Engine",
    title: "Controlled provider acquisition",
    type: "IMPLEMENTATION",
    claim: "Selected Greenhouse, Lever and Ashby listings can enter through bounded provider-specific adapters without arbitrary URL fetching.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "Controlled provider adapters", repository, path: "lib/infrastructure/market/ControlledProviderSourceAdapters.ts", ref, reviewedBlobSha: "267bd6f8201871183164007274f9d8c7508de5b4" },
      { label: "Controlled source acquisition tests", repository, path: "tests/ats2/controlled-source-acquisition.test.ts", ref, reviewedBlobSha: "1c4f2a9f5088bbc1acace663203ea752e33430f3" },
    ],
    publicability: "PUBLIC",
    context: "Adapters build fixed provider endpoints, require HTTPS/JSON, reject redirects, bound response size/time and map only source-explicit fields.",
    limitations: "The runtime is intentionally one listing at a time and manually triggered. It is not a crawler, continuous provider poller or broad synchronization worker.",
    relatedDecisionIds: ["D-CV-07"],
    relatedArchitectureIds: ["provider-adapter"],
  },
  {
    id: "E-CV-12",
    slug: "e-cv-12",
    systemId: "02",
    systemName: "CV Engine",
    title: "UNKNOWN is first-class derived state",
    type: "MODEL",
    claim: "Derived market fields remain UNKNOWN with an explicit reason when source material does not authorize a value.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "DerivedMarketInterpretation", repository, path: "lib/domain/market/DerivedMarketInterpretation.ts", ref, reviewedBlobSha: "b1b928cd353f5eb89b9650f3faacdc09cb8d053c" },
    ],
    publicability: "PUBLIC",
    context: "UNKNOWN reasons include SOURCE_SILENT, UNRECOGNIZED_SOURCE_VALUE and INVALID_SOURCE_VALUE; known fields retain source evidence and controlled derivation kind.",
    limitations: "This evidence describes current deterministic market interpretation boundaries, not every future inference method CV Engine may add.",
    relatedDecisionIds: ["D-CV-08"],
    relatedArchitectureIds: ["market-interpretation"],
  },
  {
    id: "E-CV-13",
    slug: "e-cv-13",
    systemId: "02",
    systemName: "CV Engine",
    title: "Provenance-bound Job Intelligence projection",
    type: "ARCHITECTURE",
    claim: "Only authorized source text can cross from market truth into Job Intelligence, and market metadata is not synthesized into requirement text.",
    state: "SOURCE_VERIFIED",
    sources: [
      { label: "M4B-05 execution record", repository, path: "docs/market-v0.1/MARKET-04B-05-JOB-INTELLIGENCE-PROJECTION.md", ref, reviewedBlobSha: "a7fd937eef97d4aeb366aed0d8faafafee2fb4a8" },
    ],
    publicability: "PUBLIC",
    context: "Legal parser input is either exact raw TEXT observation content or the exact source-explicit description from JSON/provider evidence; missing explicit JSON description fails closed.",
    limitations: "This bridge controls authorized parser input and provenance; it does not claim that downstream requirement parsing is universally correct.",
    relatedDecisionIds: ["D-CV-09"],
    relatedArchitectureIds: ["market-job-projection", "job-intelligence"],
  },
  {
    id: "E-CV-14",
    slug: "e-cv-14",
    systemId: "02",
    systemName: "CV Engine",
    title: "Exact market JobSnapshot assessment integration",
    type: "ARCHITECTURE",
    claim: "Market Application Intelligence consumes the exact durable market-provenanced JobSnapshot rather than rebuilding job truth at assessment time.",
    state: "TEST_ARTIFACT",
    sources: [
      { label: "M4B-06 execution record", repository, path: "docs/market-v0.1/MARKET-04B-06-MARKET-ASSESSMENT-INTEGRATION.md", ref, reviewedBlobSha: "e5900b757fccbb807d715650c6535d5319364c6a" },
      { label: "Market assessment integration tests", repository, path: "tests/ats2/market-opportunity-assessment-integration.test.ts", ref, reviewedBlobSha: "68431d3b209bba0e6478bba4bf223b88db9ce07a" },
    ],
    publicability: "PUBLIC",
    context: "The route selects JobSnapshotId, matching reads the stored requirement set, and OpportunityHistory preserves the exact snapshot identity/provenance.",
    limitations: "M4B-07 opportunity identity/lifecycle remains next: cross-source deduplication, OPEN/CLOSED/STALE and freshness semantics are not claimed complete.",
    relatedDecisionIds: ["D-CV-09"],
    relatedArchitectureIds: ["job-snapshot", "opportunity-assessment", "opportunity-history"],
  },
] as const;
