export const cvEngineCase = {
  id: "02",
  name: "CV Engine",
  label: "APPLICATION INTELLIGENCE",
  role: "Primary Builder",
  state: "ACTIVE",
  thesis:
    "A decision system for comparing career evidence with opportunity truth without allowing market data, inference, or recommendations to rewrite what the candidate can actually prove.",
  truthLayers: [
    {
      id: "career",
      index: "01",
      title: "CAREER FACT",
      detail: "Candidate-side evidence and assertions.",
      boundary: "WHAT CAN BE PROVED",
    },
    {
      id: "market",
      index: "02",
      title: "MARKET FACT",
      detail: "What a job/source explicitly says.",
      boundary: "WHAT THE SOURCE SAID",
    },
    {
      id: "analysis",
      index: "03",
      title: "DERIVED ANALYSIS",
      detail: "Matching, normalization, interpretation.",
      boundary: "WHAT THE SYSTEM COMPUTED",
    },
    {
      id: "recommendation",
      index: "04",
      title: "RECOMMENDATION",
      detail: "A bounded suggested action.",
      boundary: "WHAT TO DO NEXT",
    },
  ],
  problemSignals: [
    {
      id: "P-CV-01",
      title: "The job description becomes candidate truth.",
      detail: "A requirement from the employer must never become evidence that the candidate has that capability.",
    },
    {
      id: "P-CV-02",
      title: "A rewrite upgrades responsibility.",
      detail: "Participated can become led; implemented can become designed; design can become architecture ownership.",
    },
    {
      id: "P-CV-03",
      title: "One score hides the decision path.",
      detail: "A useful decision needs evidence, gaps, uncertainty, eligibility and next action—not only a percentage.",
    },
  ],
  truthClasses: [
    ["CANDIDATE_ASSERTED", "candidate says this", "source-side assertion"],
    ["VERIFIED_FACT", "evidence/source required", "validated fact"],
    ["DERIVED_FACT", "derivation rule required", "computed candidate-side fact"],
    ["REWRITE", "source assertion required", "fact-preserving wording"],
    ["SUGGESTION", "cannot become ResumeClaim directly", "proposal only"],
  ] as const,
  matchExamples: [
    ["JavaScript", "Java", "GAP"],
    ["Azure", "AWS", "GAP"],
    ["2 documented years", "5 required years", "GAP"],
    ["collaborated", "lead engineering teams", "GAP"],
    ["work authorization absent", "US authorization required", "UNKNOWN"],
    ["TypeScript evidence", "TypeScript required", "MATCH"],
  ] as const,
  escalationExamples: [
    ["participated", "led", "NEEDS CONFIRMATION"],
    ["implemented", "designed", "NEEDS CONFIRMATION"],
    ["designed", "architected", "NEEDS CONFIRMATION"],
    ["built", "owned", "NEEDS CONFIRMATION"],
    ["built APIs", "developed APIs", "APPROVED EXAMPLE"],
  ] as const,
  assessmentStates: [
    ["READY_NOW", "YES", "APPLY"],
    ["STRONG_STRETCH", "CONSIDER", "APPLY_WITH_CAUTION"],
    ["BUILDABLE", "NOT_YET", "BUILD_FIRST"],
    ["ASPIRATIONAL", "FUTURE_TARGET", "PLAN_PATH"],
    ["LOW_ALIGNMENT", "NO", "DEPRIORITIZE"],
  ] as const,
  providers: [
    ["GREENHOUSE", "boardToken + jobId"],
    ["LEVER", "site + postingId"],
    ["ASHBY", "jobBoardName + hosted job URL selector"],
  ] as const,
  providerRules: [
    "fixed provider hosts",
    "HTTPS only",
    "redirect reject",
    "JSON only",
    "abortable timeout",
    "2 MiB response ceiling",
    "provider identity validation",
    "no arbitrary URL fetch",
  ],
  unknownReasons: ["SOURCE_SILENT", "UNRECOGNIZED_SOURCE_VALUE", "INVALID_SOURCE_VALUE"],
  evidence: [
    ["E-CV-01", "Career evidence / assertion boundary", "SOURCE VERIFIED"],
    ["E-CV-02", "Job truth remains job-side", "SOURCE VERIFIED"],
    ["E-CV-03", "Evidence-backed requirement matching", "SOURCE + TEST ARTIFACT"],
    ["E-CV-04", "Responsibility escalation guardrails", "SOURCE + TEST ARTIFACT"],
    ["E-CV-05", "Claim Ledger / resume provenance", "SOURCE VERIFIED"],
    ["E-CV-06", "Content-addressed ResumeVersion", "SOURCE + TEST ARTIFACT"],
    ["E-CV-07", "Durable Career Vault graph", "TEST ARTIFACT"],
    ["E-CV-08", "Opportunity assessment", "SOURCE VERIFIED"],
    ["E-CV-09", "CareerTarget CAN / WANT boundary", "SOURCE VERIFIED"],
    ["E-CV-10", "Market state / occurrence boundary", "SOURCE VERIFIED"],
    ["E-CV-11", "Controlled provider acquisition", "SOURCE + TEST ARTIFACT"],
    ["E-CV-12", "UNKNOWN derived-state discipline", "SOURCE VERIFIED"],
    ["E-CV-13", "Provenance-bound Job Intelligence projection", "DOCUMENTED COMPLETE"],
    ["E-CV-14", "Exact market JobSnapshot assessment", "SOURCE + TEST ARTIFACT"],
  ] as const,
  verification: [
    ["Candidate truth requires provenance", "SOURCE / TEST", "E-CV-01"],
    ["Requirement match preserves GAP / UNKNOWN", "SOURCE / TEST", "E-CV-03"],
    ["Responsibility escalation is checked", "TEST ARTIFACT", "E-CV-04"],
    ["Resume wording traces to candidate assertions", "TEST ARTIFACT", "E-CV-06"],
    ["Career Vault rejects tampered rendered content", "TEST ARTIFACT", "E-CV-07"],
    ["Recommendation is not employer probability", "SOURCE BOUNDARY", "E-CV-08"],
    ["Provider ingress is bounded", "SOURCE / TEST", "E-CV-11"],
    ["Market UNKNOWN is first-class", "SOURCE", "E-CV-12"],
    ["Exact market JobSnapshot is consumed", "SOURCE / TEST", "E-CV-14"],
    ["Opportunity identity / OPEN-CLOSED-STALE lifecycle", "NEXT / NOT CLAIMED", "M4B-07"],
  ] as const,
} as const;
