export const profile = {
  name: "Eduardo Merino",
  fullName: "Eduardo Farid Merino Cordova",
  role: "Software Engineer",
  specialty: "Full Stack · Applied AI",
  proposition: "I build useful software products from idea to working release.",
  scope: "Full-stack products, automation and applied AI — designed, built and shipped end to end.",
  email: "farid.merino1673@gmail.com",
  location: "Lima, Peru",
  experience: "Professional software development since Feb 2025",
  education: "Systems & Informatics Engineering · final stage",
  linkedin: "https://www.linkedin.com/in/emerinoc",
  github: "https://github.com/Em3rc0d",
  cv: "/resume",
  cvDownload: "https://harvard-ats-resume.vercel.app/api/resume-improvements?runId=1e3aac43-5847-4f0d-85ad-57a6c2d6ea63&format=pdf",
  portrait: "/portrait/eduardo.webp",
} as const;
