import type { SystemRecord } from "@/lib/content/types";

export const systems: readonly SystemRecord[] = [
  {
    id: "01",
    slug: "autopulse",
    name: "AutoPulse",
    label: "REAL-WORLD TELEMETRY",
    summary:
      "A telemetry system focused on making unreliable real-world signals persistable, recoverable, and usable.",
    path: ["Capture", "Persist", "Recover", "Analyze"],
    role: "FLAGSHIP",
    ownership: "Primary Builder",
    state: "ACTIVE_RND",
    publicability: "PUBLIC",
    href: "/systems/autopulse",
  },
  {
    id: "02",
    slug: "cv-engine",
    name: "CV Engine",
    label: "APPLICATION INTELLIGENCE",
    summary:
      "An evidence-driven system for understanding opportunities, measuring fit, and deciding how to compete.",
    path: ["Evidence", "Snapshot", "Match", "Decision", "Application"],
    role: "FLAGSHIP",
    ownership: "Primary Builder",
    state: "ACTIVE",
    publicability: "PUBLIC",
    href: "/systems/cv-engine",
  },
  {
    id: "03",
    slug: "graph",
    name: "Graph",
    label: "KNOWLEDGE / RELATIONSHIPS",
    summary: "Supporting system candidate pending final public evidence contract.",
    path: ["Model", "Relate", "Inspect"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PUBLIC",
  },
  {
    id: "04",
    slug: "infra-monitor",
    name: "Infra Monitor",
    label: "OBSERVABILITY",
    summary: "Supporting system candidate pending final public evidence contract.",
    path: ["Observe", "Detect", "Respond"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PUBLIC",
  },
  {
    id: "05",
    slug: "prodagentic",
    name: "prodAgentic",
    label: "APPLIED AI / AGENTS",
    summary: "Supporting system candidate pending final public evidence contract.",
    path: ["Context", "Act", "Verify"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PUBLIC",
  },
  {
    id: "06",
    slug: "gpets",
    name: "GPets",
    label: "FULL-STACK PRODUCT",
    summary: "A software-development challenge project retained as supporting evidence.",
    path: ["Model", "Build", "Deliver"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "ARCHIVED",
    publicability: "PUBLIC",
  },
  {
    id: "R",
    slug: "rag",
    name: "RAG",
    label: "RESERVED",
    summary: "Not publicly routed until its evidence and publicability contract is cleared.",
    path: ["Reserved"],
    role: "RESERVED",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PRIVATE",
  },
] as const;

export const flagshipSystems = systems.filter(
  (system) => system.role === "FLAGSHIP" && system.publicability !== "PRIVATE",
);
