import type { SystemRecord } from "@/lib/content/types";

export const systems: readonly SystemRecord[] = [
  {
    id: "01",
    slug: "autopulse",
    name: "AutoPulse",
    label: "REAL-WORLD TELEMETRY",
    summary:
      "A telemetry system focused on making unreliable real-world signals persistable, recoverable, and usable.",
    path: ["Capture", "Persist", "Recover", "Analyze"],
    role: "FLAGSHIP",
    ownership: "Primary Builder",
    state: "ACTIVE_RND",
    publicability: "PUBLIC",
    href: "/systems/autopulse",
  },
  {
    id: "02",
    slug: "cv-engine",
    name: "CV Engine",
    label: "APPLICATION INTELLIGENCE",
    summary:
      "An evidence-driven system for understanding opportunities, measuring fit, and deciding how to compete.",
    path: ["Evidence", "Snapshot", "Match", "Decision", "Application"],
    role: "FLAGSHIP",
    ownership: "Primary Builder",
    state: "ACTIVE",
    publicability: "PUBLIC",
    href: "/systems/cv-engine",
  },
  {
    id: "03",
    slug: "infrastructure-site-mapper",
    name: "Infrastructure Site Mapper",
    label: "PROFESSIONAL / INFRASTRUCTURE OPERATIONS",
    summary:
      "An abstracted professional record showing how physical infrastructure hierarchy, spatial data, device context, and operational views were turned into working software.",
    path: ["Hierarchy", "Spatial Model", "Device Context", "Operational Views"],
    role: "SUPPORT",
    ownership: "Software Developer — implementation & hardening",
    state: "VERIFIED",
    publicability: "ABSTRACTED",
    href: "/systems/infrastructure-site-mapper",
  },
  {
    id: "04",
    slug: "gpets",
    name: "GPets",
    label: "FULL-STACK / REAL-TIME PRODUCT",
    summary:
      "A full-stack challenge system connecting a browser map, authenticated REST APIs, persistence, realtime updates, and offline-safe synchronization.",
    path: ["Browser", "API", "Service", "Data", "Realtime"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "ARCHIVED",
    publicability: "PUBLIC",
    href: "/systems/gpets",
  },
  {
    id: "H1",
    slug: "graph",
    name: "Graph",
    label: "KNOWLEDGE / RELATIONSHIPS",
    summary: "Held outside public routing until its evidence contract is strong enough.",
    path: ["Model", "Relate", "Inspect"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PRIVATE",
  },
  {
    id: "H2",
    slug: "infra-monitor",
    name: "Infra Monitor",
    label: "OBSERVABILITY",
    summary: "Held outside public routing until its evidence contract is strong enough.",
    path: ["Observe", "Detect", "Respond"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PRIVATE",
  },
  {
    id: "H3",
    slug: "prodagentic",
    name: "prodAgentic",
    label: "APPLIED AI / AGENTS",
    summary: "Held outside public routing until its portfolio evidence contract is frozen.",
    path: ["Context", "Act", "Verify"],
    role: "SUPPORT",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PRIVATE",
  },
  {
    id: "R",
    slug: "rag",
    name: "RAG",
    label: "RESERVED",
    summary: "Not publicly routed until its evidence and publicability contract is cleared.",
    path: ["Reserved"],
    role: "RESERVED",
    ownership: "Builder",
    state: "EXPERIMENTAL",
    publicability: "PRIVATE",
  },
] as const;

export const flagshipSystems = systems.filter(
  (system) => system.role === "FLAGSHIP" && system.publicability !== "PRIVATE",
);
