import Link from 'next/link';
import { notFound } from 'next/navigation';
import { findNoteBySlug, publicNotes } from '@/content/notes';
import { findEvidenceBySlug } from '@/content/evidence-index';
import { pageMetadata } from '@/lib/metadata';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return publicNotes.map(note=>({slug:note.slug}));}
export async function generateMetadata({params}:Props){const {slug}=await params;const note=findNoteBySlug(slug);return note?pageMetadata(note.title,note.thesis,`/notes/${slug}`):{};}
export default async function NotePage({params}:Props){const {slug}=await params;const note=findNoteBySlug(slug);if(!note)notFound();const records=note.relatedEvidenceIds.map(id=>findEvidenceBySlug(id.toLowerCase())).filter(x=>x!==undefined);return <main id="main-content" className="paper reading-main" tabIndex={-1}><article className="container reading-article"><Link href="/notes" className="back-link">← Engineering notebook</Link><header className="reading-heading"><p className="eyebrow">{note.territory} / {note.state==='EXPLORING'?'Exploring':'Implementation note'}</p><h1>{note.title}</h1><p className="lead">{note.thesis}</p><p className="note-byline">Eduardo Merino{note.systemName?` · ${note.systemName}`:''}</p></header><div className="prose note-body">{note.systemName==='CV Engine'&&<aside className="reading-notice">This note describes the previously reviewed CV Engine lineage. The current product is being rebuilt; the historical evidence does not certify the new runtime.</aside>}{note.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></section>)}{note.currentBoundary&&<aside className="reading-notice"><h2>Scope of this note</h2><p>{note.currentBoundary}</p></aside>}</div><footer className="reading-relations"><h2>Follow the reasoning</h2>{note.systemHref&&<Link className="text-link" href={note.systemHref.split('#')[0]}>Explore {note.systemName} <span aria-hidden="true">↗</span></Link>}{records.map(record=><Link className="relation-link" key={record.slug} href={`/evidence/${record.slug}`}>{record.title} <span aria-hidden="true">↗</span></Link>)}<Link className="text-link" href="/contact">Start a conversation <span aria-hidden="true">↗</span></Link></footer></article></main>}
